### ISSUE TITLE
###multilabel-indicator format is not supported

### ISSUE THREAD

**Issue by pavannaikmu** [manifoldailearning/Youtube#2]
sir, 
when i try to run the code i get an error i,e
"**ValueError: multilabel-indicator format is not supported**" please explain how handle this error

![multi](https://user-images.githubusercontent.com/62498125/92347138-3eec9080-f08c-11ea-983f-1d24e135ebcd.png)
![multi2](https://user-images.githubusercontent.com/62498125/92347141-41e78100-f08c-11ea-8420-ff068403dc0b.png)

link of the code on which i am working
[https://github.com/OmarMedhat22/Iris-Recognition-CASIA-Iris-Thousand/blob/master/iris_classification_2.ipynb](url)

**Comment by manifoldailearning** [comment]
As mentioned earlier, roc_curve do not support Multi class, 
it would work only on Binary Classification
